In [8]:
from pathlib import Path
import sys
import numpy as np
from stable_baselines3.ppo import PPO

PROJECT_ROOT_DIR = Path().absolute().parent.parent
if str(PROJECT_ROOT_DIR.absolute()) not in sys.path:
    sys.path.append(str(PROJECT_ROOT_DIR.absolute()))

from envs.custom_cartpole import CustomCartPoleEnv
from utils.collect_samples import collect_samples

PROJECT_ROOT_DIR

PosixPath('/home/ucav/pythonprojects/rl_sys_id')

In [9]:
env_config_real = {
    "gravity": 9.5,
    "masscart": 1.1,
    "masspole": 0.09,
    "length": 0.55,
    "force_mag": 10.0,
    "tau": 0.02,
}
env_real = CustomCartPoleEnv.get_env_from_config(config=env_config_real)

policy_class = PPO
policy_path = PROJECT_ROOT_DIR / "checkpoints/custom_cartpole/ppo/best_model.zip"
algo = policy_class.load(policy_path, env=env_real)

collect_real_sample_num = 10000

obs_real, act_real, next_obs_real = collect_samples(
    policy=algo.policy,
    env=env_real,
    num_samples=collect_real_sample_num,
    deterministic=True,
)

print(f"length of obs_real: {len(obs_real)}, length of act_real: {len(act_real)}, length of next_obs_real: {len(next_obs_real)}")
print(type(obs_real), type(act_real), type(next_obs_real))
print(obs_real)
print(act_real)
print(next_obs_real)

np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/obs_real.npy", obs_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/act_real.npy", act_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/next_obs_real.npy", next_obs_real, allow_pickle=True)

reset num: 20
length of obs_real: 10000, length of act_real: 10000, length of next_obs_real: 10000
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[ 0.01369617 -0.02302133 -0.04590265 -0.04834723]
 [ 0.01323574 -0.20064893 -0.04686959  0.1817283 ]
 [ 0.00922276 -0.02196545 -0.04323503 -0.07380246]
 ...
 [-0.29560056 -0.12764272 -0.00338932  0.21436577]
 [-0.2981534   0.05056946  0.00089799 -0.02952759]
 [-0.29714203  0.22873291  0.00030744 -0.272245  ]]
[0 1 0 ... 1 1 0]
[[ 0.01323574 -0.20064893 -0.04686959  0.1817283 ]
 [ 0.00922276 -0.02196545 -0.04323503 -0.07380246]
 [ 0.00878346 -0.19962606 -0.04471108  0.1570373 ]
 ...
 [-0.2981534   0.05056946  0.00089799 -0.02952759]
 [-0.29714203  0.22873291  0.00030744 -0.272245  ]
 [-0.29256737  0.0505557  -0.00513746 -0.02919643]]


In [10]:
a = np.load(str(PROJECT_ROOT_DIR / "data/custom_cartpole/obs_real.npy"), allow_pickle=True)
a

array([[ 0.01369617, -0.02302133, -0.04590265, -0.04834723],
       [ 0.01323574, -0.20064893, -0.04686959,  0.1817283 ],
       [ 0.00922276, -0.02196545, -0.04323503, -0.07380246],
       ...,
       [-0.29560056, -0.12764272, -0.00338932,  0.21436577],
       [-0.2981534 ,  0.05056946,  0.00089799, -0.02952759],
       [-0.29714203,  0.22873291,  0.00030744, -0.272245  ]],
      dtype=float32)