In [23]:
from pathlib import Path
import sys
import numpy as np
from stable_baselines3.ppo import PPO

PROJECT_ROOT_DIR = Path().absolute().parent.parent
if str(PROJECT_ROOT_DIR.absolute()) not in sys.path:
    sys.path.append(str(PROJECT_ROOT_DIR.absolute()))

from envs.custom_cartpole import CustomCartPoleEnv
from utils.collect_samples import collect_samples

PROJECT_ROOT_DIR

PosixPath('/home/gxd/code/rl_sys_id')

In [24]:
env_config_real = {
    "gravity": 9.8,
    "masscart": 1.5,
    "masspole": 0.05,
    "length": 0.5,
    "force_mag": 10.0,
    "tau": 0.02,
}
env_real = CustomCartPoleEnv.get_env_from_config(config=env_config_real)

policy_class = PPO
policy_path = PROJECT_ROOT_DIR / "checkpoints/custom_cartpole/ppo/best_model.zip"
algo = policy_class.load(policy_path, env=env_real)

collect_real_sample_num = 3000

obs_real, act_real, next_obs_real = collect_samples(
    policy=algo.policy,
    env=env_real,
    num_samples=collect_real_sample_num,
    deterministic=True,
)

print(f"length of obs_real: {len(obs_real)}, length of act_real: {len(act_real)}, length of next_obs_real: {len(next_obs_real)}")
print(type(obs_real), type(act_real), type(next_obs_real))
print(obs_real)
print(act_real)
print(next_obs_real)

np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/obs_real.npy", obs_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/act_real.npy", act_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_cartpole/next_obs_real.npy", next_obs_real, allow_pickle=True)

length of obs_real: 3000, length of act_real: 3000, length of next_obs_real: 3000
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[ 0.01369617 -0.02302133 -0.04590265 -0.04834723]
 [ 0.01323574 -0.15502313 -0.04686959  0.13595626]
 [ 0.01013528 -0.02257179 -0.04415047 -0.07627718]
 ...
 [-0.10253495  0.10692363 -0.00173933 -0.1047003 ]
 [-0.10039648 -0.02529932 -0.00383333  0.09312246]
 [-0.10090246  0.10695066 -0.00197088 -0.10637804]]
[0 1 0 ... 0 1 0]
[[ 0.01323574 -0.15502313 -0.04686959  0.13595626]
 [ 0.01013528 -0.02257179 -0.04415047 -0.07627718]
 [ 0.00968384 -0.15458263 -0.04567601  0.1085701 ]
 ...
 [-0.10039648 -0.02529932 -0.00383333  0.09312246]
 [-0.10090246  0.10695066 -0.00197088 -0.10637804]
 [-0.09876345 -0.02527117 -0.00409845  0.09137487]]


In [25]:
a = np.load(str(PROJECT_ROOT_DIR / "data/custom_cartpole/obs_real.npy"), allow_pickle=True)
a

array([[ 0.01369617, -0.02302133, -0.04590265, -0.04834723],
       [ 0.01323574, -0.15502313, -0.04686959,  0.13595626],
       [ 0.01013528, -0.02257179, -0.04415047, -0.07627718],
       ...,
       [-0.10253495,  0.10692363, -0.00173933, -0.1047003 ],
       [-0.10039648, -0.02529932, -0.00383333,  0.09312246],
       [-0.10090246,  0.10695066, -0.00197088, -0.10637804]],
      dtype=float32)