In [3]:
from pathlib import Path
import sys
import numpy as np
from stable_baselines3.ppo import PPO
from stable_baselines3.sac import SAC

PROJECT_ROOT_DIR = Path().absolute().parent.parent
if str(PROJECT_ROOT_DIR.absolute()) not in sys.path:
    sys.path.append(str(PROJECT_ROOT_DIR.absolute()))

from envs.custom_pendulum import CustomPendulumEnv
from utils.collect_samples import collect_samples

PROJECT_ROOT_DIR

PosixPath('/home/ucav/pythonprojects/rl_sys_id')

In [4]:
env_config_real = {
    "g": 9.5,
    "m": 0.9,
    "l": 1.2,
}
env_real = CustomPendulumEnv.get_env_from_config(config=env_config_real)

policy_class = SAC
policy_path = PROJECT_ROOT_DIR / "checkpoints/custom_pendulum/sac/g_10_0_m_1_0_l_1_0/seed_1/best_model.zip"
algo = policy_class.load(policy_path, env=env_real)

collect_real_sample_num = 1000

obs_real, act_real, next_obs_real = collect_samples(
    policy=algo.policy,
    env=env_real,
    num_samples=collect_real_sample_num,
    deterministic=True,
)

print(f"length of obs_real: {len(obs_real)}, length of act_real: {len(act_real)}, length of next_obs_real: {len(next_obs_real)}")
print(type(obs_real), type(act_real), type(next_obs_real))
print(obs_real)
print(act_real)
print(next_obs_real)

np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/obs_real.npy", obs_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/act_real.npy", act_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/next_obs_real.npy", next_obs_real, allow_pickle=True)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
length of obs_real: 1000, length of act_real: 1000, length of next_obs_real: 1000
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[ 6.5201628e-01  7.5820500e-01 -4.6042657e-01]
 [ 6.4545077e-01  7.6380187e-01  1.7254764e-01]
 [ 6.1414760e-01  7.8919119e-01  8.0615777e-01]
 ...
 [ 9.9975193e-01  2.2273311e-02 -8.1423099e-09]
 [ 9.9975193e-01  2.2273313e-02  3.1779308e-08]
 [ 9.9975193e-01  2.2273311e-02 -3.7734829e-08]]
[[ 1.5793056 ]
 [ 1.5560877 ]
 [ 0.7052851 ]
 [-0.352378  ]
 [ 1.0829139 ]
 [ 1.8329611 ]
 [ 1.9228034 ]
 [ 1.9496074 ]
 [ 1.9294283 ]
 [ 1.9750915 ]
 [ 1.9559026 ]
 [ 1.9790652 ]
 [ 1.9383132 ]
 [-1.4275496 ]
 [-1.5460278 ]
 [ 0.12307358]
 [-0.74897194]
 [-1.3830405 ]
 [-1.9751018 ]
 [-1.977513  ]
 [-1.9564319 ]
 [-1.9813957 ]
 [-1.8879988 ]
 [-0.79338646]
 [ 0.7621517 ]
 [ 1.0838456 ]
 [ 1.5105326 ]
 [ 1.3780446 ]
 [ 1.3672144 ]
 [ 1.41329   ]
 [ 1.4753349 ]
 [ 1.53057

In [5]:
a = np.load(str(PROJECT_ROOT_DIR / "data/custom_pendulum/obs_real.npy"), allow_pickle=True)
a

array([[ 6.5201628e-01,  7.5820500e-01, -4.6042657e-01],
       [ 6.4545077e-01,  7.6380187e-01,  1.7254764e-01],
       [ 6.1414760e-01,  7.8919119e-01,  8.0615777e-01],
       ...,
       [ 9.9975193e-01,  2.2273311e-02, -8.1423099e-09],
       [ 9.9975193e-01,  2.2273313e-02,  3.1779308e-08],
       [ 9.9975193e-01,  2.2273311e-02, -3.7734829e-08]], dtype=float32)