In [1]:
from pathlib import Path
import sys
import numpy as np
from stable_baselines3.ppo import PPO
from stable_baselines3.sac import SAC

PROJECT_ROOT_DIR = Path().absolute().parent.parent
if str(PROJECT_ROOT_DIR.absolute()) not in sys.path:
    sys.path.append(str(PROJECT_ROOT_DIR.absolute()))

from envs.custom_pendulum import CustomPendulumEnv
from utils.collect_samples import collect_samples

PROJECT_ROOT_DIR

PosixPath('/home/gxd/code/rl_sys_id')

In [2]:
env_config_real = {
    "g": 9.5,
    "m": 0.9,
    "l": 1.2,
}
env_real = CustomPendulumEnv.get_env_from_config(config=env_config_real)

policy_class = SAC
policy_path = PROJECT_ROOT_DIR / "checkpoints/custom_pendulum/sac/g_10_0_m_1_0_l_1_0/seed_1/best_model.zip"
algo = policy_class.load(policy_path, env=env_real)

collect_real_sample_num = 1000

obs_real, act_real, next_obs_real = collect_samples(
    policy=algo.policy,
    env=env_real,
    num_samples=collect_real_sample_num,
    deterministic=True,
)

print(f"length of obs_real: {len(obs_real)}, length of act_real: {len(act_real)}, length of next_obs_real: {len(next_obs_real)}")
print(type(obs_real), type(act_real), type(next_obs_real))
print(obs_real)
print(act_real)
print(next_obs_real)

np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/obs_real.npy", obs_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/act_real.npy", act_real, allow_pickle=True)
np.save(PROJECT_ROOT_DIR / "data/custom_pendulum/next_obs_real.npy", next_obs_real, allow_pickle=True)

Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.
length of obs_real: 1000, length of act_real: 1000, length of next_obs_real: 1000
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
[[ 6.5201628e-01  7.5820500e-01 -4.6042657e-01]
 [ 6.4545077e-01  7.6380187e-01  1.7254767e-01]
 [ 6.1414760e-01  7.8919119e-01  8.0615783e-01]
 ...
 [ 9.9975193e-01  2.2273369e-02  3.6376992e-08]
 [ 9.9975193e-01  2.2273369e-02 -3.3459902e-10]
 [ 9.9975193e-01  2.2273367e-02 -3.7056118e-08]]
[[ 1.5793059 ]
 [ 1.556088  ]
 [ 0.7052851 ]
 [-0.35237753]
 [ 1.0829134 ]
 [ 1.8329611 ]
 [ 1.9228036 ]
 [ 1.9496074 ]
 [ 1.9294286 ]
 [ 1.9750915 ]
 [ 1.9559026 ]
 [ 1.9790652 ]
 [ 1.9383132 ]
 [-1.42755   ]
 [-1.5460268 ]
 [ 0.12307072]
 [-0.7489706 ]
 [-1.3830402 ]
 [-1.9751018 ]
 [-1.977513  ]
 [-1.9564319 ]
 [-1.9813957 ]
 [-1.8879989 ]
 [-0.7933866 ]
 [ 0.7621527 ]
 [ 1.0838456 ]
 [ 1.5105324 ]
 [ 1.3780448 ]
 [ 1.3672149 ]
 [ 1.4132893 ]
 [ 1.4753346 ]
 [ 1.53057

In [3]:
a = np.load(str(PROJECT_ROOT_DIR / "data/custom_pendulum/obs_real.npy"), allow_pickle=True)
a

array([[ 6.5201628e-01,  7.5820500e-01, -4.6042657e-01],
       [ 6.4545077e-01,  7.6380187e-01,  1.7254767e-01],
       [ 6.1414760e-01,  7.8919119e-01,  8.0615783e-01],
       ...,
       [ 9.9975193e-01,  2.2273369e-02,  3.6376992e-08],
       [ 9.9975193e-01,  2.2273369e-02, -3.3459902e-10],
       [ 9.9975193e-01,  2.2273367e-02, -3.7056118e-08]], dtype=float32)